services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://backend:7000"
    ports:
      - "7001:7001"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      # Persist database data
      - pgdata:/var/lib/postgresql/data
      # Automatically run schema.sql on first startup
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
