services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://backend:7000"
    ports:
      - "7001:7001"
    depends_on:
      - backend

  db:
    image: postgres:16
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
